version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: securedash_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: securedash
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: securedash_backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      MONGO_URI: mongodb://root:rootpass@mongo:27017/securedash?authSource=admin
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: securedash_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo_data:
